version: '3.7'

services:
  traefik:
    image: traefik:2.3
    restart: unless-stopped
    healthcheck:
      test: traefik healthcheck
      interval: 2s
      timeout: 10s
      retries: 5
      start_period: 5s
    environment:
      TRAEFIK_DOMAIN:
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${pwd}/lib/docker/compose/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ${pwd}/lib/docker/compose/traefik/config.yml:/etc/traefik/config.yml:ro
      - ./certs:/etc/certs:ro
    networks:
      - ${TRAEFIK_NETWORK:-proxy}
    labels:
      traefik.enable: true
      traefik.http.routers.traefik: true
