version: '3.7'
services:
# ==============================================================================
  web:
    image: verbral/php-theia:7.4
    working_dir: /home/project
    environment:
      ENVIRONMENT:
      APACHE_DOCUMENT_ROOT: /home/project/web
      PHP_EXTENSION_BLACKFIRE: 1
      PHP_EXTENSION_GD: 1
      PHP_EXTENSION_BCMATH: 1
      PHP_INI_ERROR_REPORTING: E_ALL
      PHP_INI_MEMORY_LIMIT: 2g
      WAKATIME_API_KEY:
      GIT_USER_NAME:
      GIT_USER_EMAIL:
      SOCIAL_AUTH_FACEBOOK_APP_ID:
      SOCIAL_AUTH_FACEBOOK_APP_SECRET:
      SOCIAL_AUTH_GOOGLE_CLIENT_ID:
      SOCIAL_AUTH_GOOGLE_CLIENT_SECRET:
      GOOGLE_MAPS_API_KEY:
    volumes:
      - ${PWD}:/home/project
      - ~/.ssh:/home/docker/.ssh
      - ~/.composer:/home/docker/.composer
    labels:
      traefik.enable: true
      traefik.http.routers.dev.rule: Host(`dev.${TRAEFIK_DOMAIN}`)
      traefik.http.routers.dev.tls: true
      traefik.http.routers.dev.service: dev
      traefik.http.services.dev.loadbalancer.server.port: 80
      traefik.http.routers.ide.rule: Host(`ide.${TRAEFIK_DOMAIN}`)
      traefik.http.routers.ide.tls: true
      traefik.http.routers.ide.service: ide
      traefik.http.services.ide.loadbalancer.server.port: 3000
    networks:
      - proxy
    ports:
      - 80
      - 3000
# ==============================================================================
  selenium:
    image: selenium/standalone-chrome
# ==============================================================================
  smtp:
    image: tophfr/mailcatcher
    ports:
      - 80
    networks:
      - proxy
# ==============================================================================
  # ngrok:
  #   image: wernight/ngrok:latest
  #   ports:
  #     - 4040:4040
  #   environment:
  #     NGROK_PROTOCOL: http
  #     NGROK_PORT: web:80
  #     NGROK_AUTH:
  #     NGROK_USERNAME:
  #     NGROK_PASSWORD:
  #     NGROK_BINDTLS: 'true'
  #   networks:
  #     - proxy
# ==============================================================================
#  backstop:
#    image: backstopjs/backstopjs
#    volumes:
#      - ${PWD}/tests/backstop:/src
#    user: 1000:1000
# ==============================================================================
#  blackfire:
#    image: blackfire/blackfire
#    environment:
#        - BLACKFIRE_CLIENT_ID
#        - BLACKFIRE_CLIENT_TOKEN
#        - BLACKFIRE_SERVER_ID
#        - BLACKFIRE_SERVER_TOKEN
# ==============================================================================
