version: '3.7'
services:

  web-prod:
    image: docker.pkg.github.com/verbruggenalex/appointment/prod:latest
    working_dir: /var/www/html
    environment:
      SOCIAL_AUTH_FACEBOOK_APP_ID:
      SOCIAL_AUTH_FACEBOOK_APP_SECRET:
      SOCIAL_AUTH_GOOGLE_CLIENT_ID:
      SOCIAL_AUTH_GOOGLE_CLIENT_SECRET:
      GOOGLE_MAPS_API_KEY:
    volumes:
      - ${PWD}:/var/www/html
    labels:
      traefik.enable: true
      traefik.http.routers.production.tls: true
      traefik.http.routers.production.middlewares: production-basicauth
      traefik.http.routers.production.rule: Host(`production.${TRAEFIK_DOMAIN}`)
      traefik.http.middlewares.production-basicauth.basicauth.users: ${TRAEFIK_BASIC_AUTH}
      traefik.http.routers.pre-production.tls: true
      traefik.http.routers.pre-production.middlewares: pre-production-basicauth
      traefik.http.routers.pre-production.rule: Host(`pre-production.${TRAEFIK_DOMAIN}`)
      traefik.http.middlewares.pre-production-basicauth.basicauth.users: ${TRAEFIK_BASIC_AUTH}
      traefik.http.routers.post-production.tls: true
      traefik.http.routers.post-production.middlewares: post-production-basicauth
      traefik.http.routers.post-production.rule: Host(`post-production.${TRAEFIK_DOMAIN}`)
      traefik.http.middlewares.post-production-basicauth.basicauth.users: ${TRAEFIK_BASIC_AUTH}
    networks:
      - proxy

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=drupal
    networks:
      - proxy
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:

networks:
  proxy:
    external: true
    name: ${TRAEFIK_NETWORK}
