name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: marceloprado/has-changed-path@v1
        id: changed-dockerfile
        with:
          paths: lib/docker/Dockerfile

      - name: Build and push Docker images
        if: steps.changed-dockerfile.outputs.changed == 'true'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u verbruggenalex --password-stdin
          docker build ./lib/docker --target prod --tag docker.pkg.github.com/verbruggenalex/appointment/prod
          docker build ./lib/docker --target ci --tag docker.pkg.github.com/verbruggenalex/appointment/ci
          docker push docker.pkg.github.com/verbruggenalex/appointment/prod
          docker push docker.pkg.github.com/verbruggenalex/appointment/ci

      - name: Setup environment
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u verbruggenalex --password-stdin
          docker network create proxy
          docker-compose up -d
          docker-compose ps

      - name: Test project
        run: |
          docker-compose exec -T web-prod composer install
          docker-compose exec -T web-prod composer test-phpcs
          docker-compose exec -T web-prod composer drupal-install-clean

