name: Docker Image CI

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: marceloprado/has-changed-path@v1
        id: changed-dockerfile
        with:
          paths: lib/docker/image/Dockerfile

      # Looks like in the future we might need some image versioning here.
      - name: Build and push Docker images
        if: steps.changed-dockerfile.outputs.changed == 'true'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u verbruggenalex --password-stdin
          docker build lib/docker/image --target prod --tag docker.pkg.github.com/verbruggenalex/appointment/prod
          docker build lib/docker/image --target ci --tag docker.pkg.github.com/verbruggenalex/appointment/ci
          docker push docker.pkg.github.com/verbruggenalex/appointment/prod
          docker push docker.pkg.github.com/verbruggenalex/appointment/ci

      - name: Setup environment
        env:
          TRAEFIK_DOMAIN: ${{ secrets.TRAEFIK_DOMAIN }}
          TRAEFIK_NETWORK: ${{ secrets.TRAEFIK_NETWORK }}
          TRAEFIK_BASIC_AUTH: ${{ secrets.TRAEFIK_BASIC_AUTH }}
        run: |
          sudo chmod 777 /var/run/docker.sock
          make mkcert_setup mkcert_install docker_network_create setup_hosts
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u verbruggenalex --password-stdin
          docker-compose -f docker-compose.ci.yml -f docker-compose.traefik.yml up -d
          sleep 5
          docker-compose ps
          curl https://post-production.localhost.com

      - name: Cache Composer
        if: startsWith(github.ref, 'refs/tags/') != true
        uses: actions/cache@v2
        with:
          path: |
            vendor/
            web/
          key: vendor-web-${{ hashFiles('composer.lock') }}

      - name: Test project
        if: startsWith(github.ref, 'refs/tags/') != true
        run: |
          docker-compose exec -T web-prod composer install --no-progress --no-suggest --ansi
          docker-compose exec -T web-prod composer test-phpcs
          docker-compose exec -T web-prod composer drupal-install-clean
          docker-compose exec -T web-prod composer test-behat

      - name: Prepare release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker-compose exec -T web-prod composer build-dist

      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            dist.tar.gz
