name: SSH Deploy

on:
  push:
    branches:
      - ssh-deploy

jobs:
  push:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy with SSH
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          passphrase: ${{ secrets.SSH_PASS }}
          script: |
            cd appointment
            git pull
            git checkout ${GITHUB_REF#refs/heads/}
            make unpack tag=1.0.28
            make deploy
