name: SSH Deploy

on:
  push:
    branches:
      - ssh-deploy

jobs:
  push:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Deploy with SSH
      uses: appleboy/ssh-action@master
      with:
        key: ${{ secrets.SSH_KEY }}
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASS }}
        script: |
          cd appointment
          ls -al
